/**
 * The BadGun class is a subclass of the Weapon class,
 * it represents a weaker weapon that is used by the student
 * character.
 * 
 * It has inherited all the instance variables and methods found in 
 * the Weapon superclass, but it has overrwritten the shoot method,
 * the shoot method is modified such that the power generated 
 * by the BadGun in each shot is only 80% of it's original power.
 * 
 * @author Palden Tamang
 * @version 1.0
 * @since 2024-10-07
 */
public class BadGun extends Weapon {

	/**
	 * This constructor is used to construct a new BadGun
	 * with the given name and power.
	 * @param name This is the name of the new BadGun.
	 * @param power This is the power of the new BadGun.
	 */
	public BadGun(String name, int power) {
		super(name,power);
	}
	
	
	/**
	 * This overriden method applies to the BadGun weapon,
	 * where it first modified the power generated by the 
	 * BadGun.
	 * 
	 * The variable originalPower stores the original power of the BadGun
	 * The variable newPower stores the modified power of the BadGun, which
	 * is 80% of it's original power, rounded down to the nearest integer.
	 * 
	 * @return int returns the power level of the BadGun.
	 */
	@Override public int shoot() {
		int originalPower= this.power;
		int newPower= (int)(originalPower*0.8);
		return(newPower);
	}
}
